WITH TABLESWITHRECORDS AS
	(SELECT RELNAME AS TABLE_NAME
		FROM PG_STAT_USER_TABLES
		WHERE SCHEMANAME = 'prod'
			AND N_LIVE_TUP > 0 -- This indicates tables with more than 0 records
),
	TABLESREFERENCINGOTHERS AS
	(SELECT TAB.TABLE_SCHEMA,
			TAB.TABLE_NAME,
			'>- no FKs' AS FOREIGN_KEYS
		FROM INFORMATION_SCHEMA.TABLES TAB
		WHERE TAB.TABLE_SCHEMA NOT IN ('information_schema','pg_catalog')
			AND TAB.TABLE_TYPE = 'BASE TABLE'
			AND TAB.TABLE_SCHEMA || '.' || TAB.TABLE_NAME NOT IN
				(SELECT DISTINCT TABLE_SCHEMA || '.' || TABLE_NAME
					FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
					WHERE CONSTRAINT_TYPE = 'FOREIGN KEY')
		ORDER BY TAB.TABLE_SCHEMA,
			TAB.TABLE_NAME),
	FINALREF AS
	(SELECT T.TABLE_NAME,
			CASE
				WHEN R.TABLE_NAME IS NOT NULL THEN 'Y' ELSE 'N'
			END AS HAS_RECORDS,
			CASE
				WHEN R.TABLE_NAME = REF.TABLE_NAME THEN 'N' ELSE 'Y'
			END AS REFERENCE_TABLE_IND
		FROM INFORMATION_SCHEMA.TABLES T
		LEFT JOIN TABLESWITHRECORDS R ON T.TABLE_NAME = R.TABLE_NAME
		LEFT JOIN TABLESREFERENCINGOTHERS REF ON T.TABLE_NAME = REF.TABLE_NAME
		WHERE T.TABLE_SCHEMA = 'prod'
		ORDER BY T.TABLE_NAME),
	DEPENDENTS AS
	(SELECT DISTINCT SUBSTRING(CON.CONRELID::REGCLASS::text,6) AS TABLE_NAME,
			SUBSTRING(CON.CONFRELID::REGCLASS::text, 6) AS DEPENDENT_NAME
		FROM PG_CONSTRAINT CON
		JOIN PG_NAMESPACE NSP ON CON.CONNAMESPACE = NSP.OID
		WHERE NSP.NSPNAME = 'prod'
			AND CONFRELID IS NOT NULL
			AND CON.CONFRELID::REGCLASS::text <> '-'
		ORDER BY TABLE_NAME),
	FINALREF2 AS
	(SELECT A.TABLE_NAME AS ALL_TABLES,
			A.HAS_RECORDS,
			A.REFERENCE_TABLE_IND ,
			B.DEPENDENT_NAME
		FROM FINALREF A
		LEFT JOIN DEPENDENTS B ON A.TABLE_NAME = B.TABLE_NAME
		ORDER BY A.TABLE_NAME),
	FINALTABLE AS
	(SELECT * ,
			CASE
				WHEN DEPENDENT_NAME IN (SELECT ALL_TABLES FROM FINALREF2 WHERE HAS_RECORDS = 'Y')
				OR (DEPENDENT_NAME IS NULL AND HAS_RECORDS = 'Y') THEN 'Y' ELSE 'N'
			END AS DEPENDENCY_MET
		FROM FINALREF2)
		
SELECT *
FROM FINALTABLE 
WHERE HAS_RECORDS = 'N' order by ALL_TABLES ASC
;