 \COPY Prod.store FROM '/Users/chelciedealmeida/Downloads/store.csv' WITH CSV HEADER;
 \COPY Prod.salesterritoryhistory FROM '/Users/chelciedealmeida/Downloads/salesterritoryhistory.csv' WITH CSV HEADER;
 \COPY Prod.salespersonquotahistory FROM '/Users/chelciedealmeida/Downloads/salespersonquotahistory.csv' WITH CSV HEADER;
 \COPY Prod.productdocument FROM '/Users/chelciedealmeida/Downloads/productdocument.csv' WITH CSV HEADER;
 \COPY Prod.purchaseorderdetail FROM '/Users/chelciedealmeida/Downloads/purchaseorderdetail.csv' WITH CSV HEADER;
 \COPY Prod.customer FROM '/Users/chelciedealmeida/Downloads/customer.csv' WITH CSV HEADER;
 \COPY Prod.salesorderheader FROM '/Users/chelciedealmeida/Downloads/salesorderheader.csv' WITH CSV HEADER;
 \COPY Prod.salesorderdetail FROM '/Users/chelciedealmeida/Downloads/salesorderdetail.csv' WITH CSV HEADER;
 \COPY Prod.salesorderheadersalesreason FROM '/Users/chelciedealmeida/Downloads/salesorderheadersalesreason.csv' WITH CSV HEADER;